In [0]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
a=np.array([[1,0,1]])
b=np.array([[1,0]])
print(a)
print(b)

[[1 0 1]]
[[1 0]]


In [0]:
model=Sequential()
h1=model.add(Dense(2,activation="sigmoid",input_dim=3))
h2=model.add(Dense(3,activation="sigmoid"))

o = model.add(Dense(2,activation="sigmoid"))

In [0]:
wt_l1=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
bias1=np.array([-0.4,0.2])
l=[]
l.append(wt_l1)
l.append(bias1)
model.layers[0].set_weights(l)
model.layers[0].get_weights()

[array([[ 0.2, -0.3],
        [ 0.4,  0.1],
        [-0.5,  0.2]], dtype=float32), array([-0.4,  0.2], dtype=float32)]

In [0]:
wt_l2=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
bias2=np.array([0.1,0.1,0.2])
l=[]
l.append(wt_l2)
l.append(bias2)
model.layers[1].set_weights(l)
model.layers[1].get_weights()

[array([[-0.3,  0.2,  0.6],
        [-0.2, -0.1, -0.2]], dtype=float32),
 array([0.1, 0.1, 0.2], dtype=float32)]

In [0]:
wt_l3=np.array([[0.3,0.2],[-0.5,0.5],[-0.7,0.2]])
bias3=np.array([0.1,0.2])
l=[]
l.append(wt_l3)
l.append(bias3)
model.layers[2].set_weights(l)
model.layers[2].get_weights()

[array([[ 0.3,  0.2],
        [-0.5,  0.5],
        [-0.7,  0.2]], dtype=float32), array([0.1, 0.2], dtype=float32)]

In [0]:
from keras.optimizers import Adam
model.compile(loss="mean_squared_error",optimizer=Adam(lr=0.9),metrics=['accuracy'])

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 9         
_________________________________________________________________
dense_12 (Dense)             (None, 2)                 8         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.fit(a,b,batch_size=1,epochs=1)

Epoch 1/1
1/1 [==============================] - 0s 266ms/step - loss: 0.4019 - acc: 0.0000e+00


In [0]:
print(model.layers[0].get_weights())
print(model.layers[1].get_weights())
print(model.layers[2].get_weights())


[array([[-0.46937388,  0.36881483],
       [ 0.4       ,  0.1       ],
       [-1.1693739 ,  0.8688148 ]], dtype=float32), array([-1.0693738,  0.8688148], dtype=float32)]
[array([[ 0.36786038, -0.46954584, -0.06952143],
       [ 0.46854377, -0.7696102 , -0.8695948 ]], dtype=float32), array([ 0.7691024 , -0.5696628 , -0.46965468], dtype=float32)]
[array([[ 0.96969   , -0.46969074],
       [ 0.16969323, -0.16969383],
       [-0.03030467, -0.46969593]], dtype=float32), array([ 0.7697062 , -0.46970654], dtype=float32)]


In [0]:
model.fit(a,b,batch_size=1,epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 2ms/step - loss: 0.0530 - acc: 1.0000
Epoch 2/300
1/1 [==============================] - 0s 2ms/step - loss: 0.0027 - acc: 1.0000
Epoch 3/300
1/1 [==============================] - 0s 3ms/step - loss: 2.7966e-04 - acc: 1.0000
Epoch 4/300
1/1 [==============================] - 0s 3ms/step - loss: 3.6933e-05 - acc: 1.0000
Epoch 5/300
1/1 [==============================] - 0s 3ms/step - loss: 7.2213e-06 - acc: 1.0000
Epoch 6/300
1/1 [==============================] - 0s 2ms/step - loss: 1.7414e-06 - acc: 1.0000
Epoch 7/300
1/1 [==============================] - 0s 2ms/step - loss: 4.9826e-07 - acc: 1.0000
Epoch 8/300
1/1 [==============================] - 0s 1ms/step - loss: 1.6440e-07 - acc: 1.0000
Epoch 9/300
1/1 [==============================] - 0s 1ms/step - loss: 6.1267e-08 - acc: 1.0000
Epoch 10/300
1/1 [==============================] - 0s 2ms/step - loss: 2.5340e-08 - acc: 1.0000
Epoch 11/300
1/1 [=============================